spring.application.name=portfolio

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8080


#####
spring.jpa.open-in-view=false

jwt.secret=emirhan_portfolio_super_secret_key_2024_very_long_string
jwt.expiration=86400000